//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.17 at 01:24:02 PM BRT 
//


package org.cogroo.tools.errorreport.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BadIntervention complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BadIntervention">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Classification">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="falseError"/>
 *               &lt;enumeration value="inappropriateDescription"/>
 *               &lt;enumeration value="inappropriateSuggestion"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Comment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Rule" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Span" type="{}Span"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BadIntervention", propOrder = {
    "classification",
    "comment",
    "rule",
    "span"
})
public class BadIntervention {

    @XmlElement(name = "Classification", required = true)
    protected BadIntervention.BadInterventionClassification classification;
    @XmlElement(name = "Comment")
    protected String comment;
    @XmlElement(name = "Rule", required = true)
    protected String rule;
    @XmlElement(name = "Span", required = true)
    protected Span span;

    /**
     * Gets the value of the classification property.
     * 
     * @return
     *     possible object is
     *     {@link BadIntervention.BadInterventionClassification }
     *     
     */
    public BadIntervention.BadInterventionClassification getClassification() {
        return classification;
    }

    /**
     * Sets the value of the classification property.
     * 
     * @param value
     *     allowed object is
     *     {@link BadIntervention.BadInterventionClassification }
     *     
     */
    public void setClassification(BadIntervention.BadInterventionClassification value) {
        this.classification = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

    /**
     * Gets the value of the rule property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRule() {
        return rule;
    }

    /**
     * Sets the value of the rule property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRule(String value) {
        this.rule = value;
    }

    /**
     * Gets the value of the span property.
     * 
     * @return
     *     possible object is
     *     {@link Span }
     *     
     */
    public Span getSpan() {
        return span;
    }

    /**
     * Sets the value of the span property.
     * 
     * @param value
     *     allowed object is
     *     {@link Span }
     *     
     */
    public void setSpan(Span value) {
        this.span = value;
    }


    /**
     * <p>Java class for null.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p>
     * <pre>
     * &lt;simpleType>
     *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *     &lt;enumeration value="falseError"/>
     *     &lt;enumeration value="inappropriateDescription"/>
     *     &lt;enumeration value="inappropriateSuggestion"/>
     *   &lt;/restriction>
     * &lt;/simpleType>
     * </pre>
     * 
     */
    @XmlType(name = "")
    @XmlEnum
    public enum BadInterventionClassification {

        @XmlEnumValue("falseError")
        FALSE_ERROR("falseError"),
        @XmlEnumValue("inappropriateDescription")
        INAPPROPRIATE_DESCRIPTION("inappropriateDescription"),
        @XmlEnumValue("inappropriateSuggestion")
        INAPPROPRIATE_SUGGESTION("inappropriateSuggestion");
        private final String value;

        BadInterventionClassification(String v) {
            value = v;
        }

        public String value() {
            return value;
        }

        public static BadIntervention.BadInterventionClassification fromValue(String v) {
            for (BadIntervention.BadInterventionClassification c: BadIntervention.BadInterventionClassification.values()) {
                if (c.value.equals(v)) {
                    return c;
                }
            }
            throw new IllegalArgumentException(v);
        }

    }

}
