//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.17 at 01:24:02 PM BRT 
//


package org.cogroo.tools.errorreport.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Version" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Text" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BadInterventions" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="BadIntervention" type="{}BadIntervention" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Omissions" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Omission" type="{}Omission" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "version",
    "text",
    "badInterventions",
    "omissions"
})
@XmlRootElement(name = "ErrorReport")
public class ErrorReport {

    @XmlElement(name = "Version", required = true)
    protected String version;
    @XmlElement(name = "Text", required = true)
    protected String text;
    @XmlElement(name = "BadInterventions")
    protected ErrorReport.BadInterventions badInterventions;
    @XmlElement(name = "Omissions")
    protected ErrorReport.Omissions omissions;

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText(String value) {
        this.text = value;
    }

    /**
     * Gets the value of the badInterventions property.
     * 
     * @return
     *     possible object is
     *     {@link ErrorReport.BadInterventions }
     *     
     */
    public ErrorReport.BadInterventions getBadInterventions() {
        return badInterventions;
    }

    /**
     * Sets the value of the badInterventions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ErrorReport.BadInterventions }
     *     
     */
    public void setBadInterventions(ErrorReport.BadInterventions value) {
        this.badInterventions = value;
    }

    /**
     * Gets the value of the omissions property.
     * 
     * @return
     *     possible object is
     *     {@link ErrorReport.Omissions }
     *     
     */
    public ErrorReport.Omissions getOmissions() {
        return omissions;
    }

    /**
     * Sets the value of the omissions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ErrorReport.Omissions }
     *     
     */
    public void setOmissions(ErrorReport.Omissions value) {
        this.omissions = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="BadIntervention" type="{}BadIntervention" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "badIntervention"
    })
    public static class BadInterventions {

        @XmlElement(name = "BadIntervention", required = true)
        protected List<BadIntervention> badIntervention;

        /**
         * Gets the value of the badIntervention property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the badIntervention property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBadIntervention().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link BadIntervention }
         * 
         * 
         */
        public List<BadIntervention> getBadIntervention() {
            if (badIntervention == null) {
                badIntervention = new ArrayList<BadIntervention>();
            }
            return this.badIntervention;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Omission" type="{}Omission" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "omission"
    })
    public static class Omissions {

        @XmlElement(name = "Omission", required = true)
        protected List<Omission> omission;

        /**
         * Gets the value of the omission property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the omission property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOmission().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Omission }
         * 
         * 
         */
        public List<Omission> getOmission() {
            if (omission == null) {
                omission = new ArrayList<Omission>();
            }
            return this.omission;
        }

    }

}
