//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.17 at 01:24:02 PM BRT 
//


package org.cogroo.tools.errorreport.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.cogroo.tools.errorreport.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.cogroo.tools.errorreport.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ErrorReport.Omissions }
     * 
     */
    public ErrorReport.Omissions createErrorReportOmissions() {
        return new ErrorReport.Omissions();
    }

    /**
     * Create an instance of {@link ErrorReport }
     * 
     */
    public ErrorReport createErrorReport() {
        return new ErrorReport();
    }

    /**
     * Create an instance of {@link IgnoreError }
     * 
     */
    public IgnoreError createIgnoreError() {
        return new IgnoreError();
    }

    /**
     * Create an instance of {@link Omission }
     * 
     */
    public Omission createOmission() {
        return new Omission();
    }

    /**
     * Create an instance of {@link BadIntervention }
     * 
     */
    public BadIntervention createBadIntervention() {
        return new BadIntervention();
    }

    /**
     * Create an instance of {@link ErrorReport.BadInterventions }
     * 
     */
    public ErrorReport.BadInterventions createErrorReportBadInterventions() {
        return new ErrorReport.BadInterventions();
    }

    /**
     * Create an instance of {@link Span }
     * 
     */
    public Span createSpan() {
        return new Span();
    }

}
