language: java
jdk:
  - oraclejdk8
  - oraclejdk9
after_success:
  - mvn clean test jacoco:report coveralls:report
notifications:
  email:
    recipients:
      - cogroo_labxp2015@googlegroups.com
    on_success: never # default: change
