//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.17 at 01:24:02 PM BRT 
//


package org.cogroo.tools.checker.rules.model;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A pair of sentences: an incorrect and a correct one
 * 
 * <p>Java class for Example complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Example">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Incorrect" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Correct" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Example", propOrder = {
    "incorrect",
    "correct"
})
public class Example
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Incorrect", required = true)
    protected String incorrect;
    @XmlElement(name = "Correct", required = true)
    protected String correct;

    /**
     * Gets the value of the incorrect property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIncorrect() {
        return incorrect;
    }

    /**
     * Sets the value of the incorrect property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIncorrect(String value) {
        this.incorrect = value;
    }

    /**
     * Gets the value of the correct property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorrect() {
        return correct;
    }

    /**
     * Sets the value of the correct property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorrect(String value) {
        this.correct = value;
    }

}
