//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.17 at 01:24:02 PM BRT 
//


package org.cogroo.tools.checker.rules.model;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A mask for a token or a tag
 * 
 * <p>Java class for Mask complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Mask">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="LexemeMask" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PrimitiveMask" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TagMask" type="{}TagMask"/>
 *         &lt;element name="TagReference" type="{}Reference"/>
 *         &lt;element name="OutOfBounds" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Mask", propOrder = {
    "lexemeMask",
    "primitiveMask",
    "tagMask",
    "tagReference",
    "outOfBounds"
})
public class Mask
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "LexemeMask")
    protected String lexemeMask;
    @XmlElement(name = "PrimitiveMask")
    protected String primitiveMask;
    @XmlElement(name = "TagMask")
    protected TagMask tagMask;
    @XmlElement(name = "TagReference")
    protected Reference tagReference;
    @XmlElement(name = "OutOfBounds")
    protected String outOfBounds;

    /**
     * Gets the value of the lexemeMask property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLexemeMask() {
        return lexemeMask;
    }

    /**
     * Sets the value of the lexemeMask property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLexemeMask(String value) {
        this.lexemeMask = value;
    }

    /**
     * Gets the value of the primitiveMask property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimitiveMask() {
        return primitiveMask;
    }

    /**
     * Sets the value of the primitiveMask property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimitiveMask(String value) {
        this.primitiveMask = value;
    }

    /**
     * Gets the value of the tagMask property.
     * 
     * @return
     *     possible object is
     *     {@link TagMask }
     *     
     */
    public TagMask getTagMask() {
        return tagMask;
    }

    /**
     * Sets the value of the tagMask property.
     * 
     * @param value
     *     allowed object is
     *     {@link TagMask }
     *     
     */
    public void setTagMask(TagMask value) {
        this.tagMask = value;
    }

    /**
     * Gets the value of the tagReference property.
     * 
     * @return
     *     possible object is
     *     {@link Reference }
     *     
     */
    public Reference getTagReference() {
        return tagReference;
    }

    /**
     * Sets the value of the tagReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reference }
     *     
     */
    public void setTagReference(Reference value) {
        this.tagReference = value;
    }

    /**
     * Gets the value of the outOfBounds property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutOfBounds() {
        return outOfBounds;
    }

    /**
     * Sets the value of the outOfBounds property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutOfBounds(String value) {
        this.outOfBounds = value;
    }

}
