//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.17 at 01:24:02 PM BRT 
//


package org.cogroo.tools.checker.rules.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Template to suggest a way to correct a grammar mistake
 * 
 * <p>Java class for Suggestion complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Suggestion">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SuggestionAsString" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Replace" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Lexeme" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="TagReference" type="{}TagReference" minOccurs="0"/>
 *                   &lt;element name="Reference" type="{}Reference" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="index" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ReplaceMapping" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="index" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *                 &lt;attribute name="key" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Swap" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="a" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *                 &lt;attribute name="b" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Suggestion", propOrder = {
    "suggestionAsString",
    "replace",
    "replaceMapping",
    "swap"
})
public class Suggestion
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "SuggestionAsString")
    protected String suggestionAsString;
    @XmlElement(name = "Replace")
    protected List<Suggestion.Replace> replace;
    @XmlElement(name = "ReplaceMapping")
    protected List<Suggestion.ReplaceMapping> replaceMapping;
    @XmlElement(name = "Swap")
    protected List<Suggestion.Swap> swap;

    /**
     * Gets the value of the suggestionAsString property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuggestionAsString() {
        return suggestionAsString;
    }

    /**
     * Sets the value of the suggestionAsString property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuggestionAsString(String value) {
        this.suggestionAsString = value;
    }

    /**
     * Gets the value of the replace property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the replace property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReplace().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Suggestion.Replace }
     * 
     * 
     */
    public List<Suggestion.Replace> getReplace() {
        if (replace == null) {
            replace = new ArrayList<Suggestion.Replace>();
        }
        return this.replace;
    }

    /**
     * Gets the value of the replaceMapping property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the replaceMapping property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReplaceMapping().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Suggestion.ReplaceMapping }
     * 
     * 
     */
    public List<Suggestion.ReplaceMapping> getReplaceMapping() {
        if (replaceMapping == null) {
            replaceMapping = new ArrayList<Suggestion.ReplaceMapping>();
        }
        return this.replaceMapping;
    }

    /**
     * Gets the value of the swap property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the swap property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSwap().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Suggestion.Swap }
     * 
     * 
     */
    public List<Suggestion.Swap> getSwap() {
        if (swap == null) {
            swap = new ArrayList<Suggestion.Swap>();
        }
        return this.swap;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Lexeme" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="TagReference" type="{}TagReference" minOccurs="0"/>
     *         &lt;element name="Reference" type="{}Reference" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="index" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "lexeme",
        "tagReference",
        "reference"
    })
    public static class Replace
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        @XmlElement(name = "Lexeme")
        protected String lexeme;
        @XmlElement(name = "TagReference")
        protected TagReference tagReference;
        @XmlElement(name = "Reference")
        protected Reference reference;
        @XmlAttribute(required = true)
        @XmlSchemaType(name = "unsignedInt")
        protected long index;

        /**
         * Gets the value of the lexeme property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLexeme() {
            return lexeme;
        }

        /**
         * Sets the value of the lexeme property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLexeme(String value) {
            this.lexeme = value;
        }

        /**
         * Gets the value of the tagReference property.
         * 
         * @return
         *     possible object is
         *     {@link TagReference }
         *     
         */
        public TagReference getTagReference() {
            return tagReference;
        }

        /**
         * Sets the value of the tagReference property.
         * 
         * @param value
         *     allowed object is
         *     {@link TagReference }
         *     
         */
        public void setTagReference(TagReference value) {
            this.tagReference = value;
        }

        /**
         * Gets the value of the reference property.
         * 
         * @return
         *     possible object is
         *     {@link Reference }
         *     
         */
        public Reference getReference() {
            return reference;
        }

        /**
         * Sets the value of the reference property.
         * 
         * @param value
         *     allowed object is
         *     {@link Reference }
         *     
         */
        public void setReference(Reference value) {
            this.reference = value;
        }

        /**
         * Gets the value of the index property.
         * 
         */
        public long getIndex() {
            return index;
        }

        /**
         * Sets the value of the index property.
         * 
         */
        public void setIndex(long value) {
            this.index = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="index" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
     *       &lt;attribute name="key" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class ReplaceMapping
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        @XmlAttribute(required = true)
        @XmlSchemaType(name = "unsignedInt")
        protected long index;
        @XmlAttribute(required = true)
        protected String key;
        @XmlAttribute(required = true)
        protected String value;

        /**
         * Gets the value of the index property.
         * 
         */
        public long getIndex() {
            return index;
        }

        /**
         * Sets the value of the index property.
         * 
         */
        public void setIndex(long value) {
            this.index = value;
        }

        /**
         * Gets the value of the key property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getKey() {
            return key;
        }

        /**
         * Sets the value of the key property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setKey(String value) {
            this.key = value;
        }

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="a" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
     *       &lt;attribute name="b" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Swap
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        @XmlAttribute(required = true)
        @XmlSchemaType(name = "unsignedInt")
        protected long a;
        @XmlAttribute(required = true)
        @XmlSchemaType(name = "unsignedInt")
        protected long b;

        /**
         * Gets the value of the a property.
         * 
         */
        public long getA() {
            return a;
        }

        /**
         * Sets the value of the a property.
         * 
         */
        public void setA(long value) {
            this.a = value;
        }

        /**
         * Gets the value of the b property.
         * 
         */
        public long getB() {
            return b;
        }

        /**
         * Sets the value of the b property.
         * 
         */
        public void setB(long value) {
            this.b = value;
        }

    }

}
